/*
 * Hacker News
 *
 * ## Welcome  This is a place to put general notes and extra information, for internal use.  To get started designing/documenting this API, select a version on the left. # Title No Description
 *
 * API version: v0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package hackernews

type SharedUser struct {
	Username string `json:"username,omitempty"`
	string   `json:",omitempty"`
}
